//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Protocols.TestManager.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Protocols.TestManager.UI.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort test execution may result in incomplete test log.
        ///Do you want to abort the execution?.
        /// </summary>
        internal static string AbortWarning {
            get {
                return ResourceManager.GetString("AbortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detection.
        /// </summary>
        internal static string Autodetection {
            get {
                return ResourceManager.GetString("Autodetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Run Auto-Detection may have impact to SUT&apos;s states (PTM may create directories or files, may establish connections with SUT and send packets, etc).
        ///Do you want to continue?.
        /// </summary>
        internal static string AutoDetectWarning {
            get {
                return ResourceManager.GetString("AutoDetectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure test suite using auto-detection.
        /// </summary>
        internal static string AutoDetectWarningTitle {
            get {
                return ResourceManager.GetString("AutoDetectWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose configuration method.
        /// </summary>
        internal static string ChooseConfigMethod {
            get {
                return ResourceManager.GetString("ChooseConfigMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure adapters.
        /// </summary>
        internal static string ConfigureAdapters {
            get {
                return ResourceManager.GetString("ConfigureAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure test case properties.
        /// </summary>
        internal static string ConfigureTestCase {
            get {
                return ResourceManager.GetString("ConfigureTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Wizard.
        /// </summary>
        internal static string ConfigureWizard {
            get {
                return ResourceManager.GetString("ConfigureWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply default value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Detect.
        /// </summary>
        internal static string DetectButton {
            get {
                return ResourceManager.GetString("DetectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detect error.
        /// </summary>
        internal static string DetectionError {
            get {
                return ResourceManager.GetString("DetectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection result.
        /// </summary>
        internal static string DetectionResult {
            get {
                return ResourceManager.GetString("DetectionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is detected not supported..
        /// </summary>
        internal static string FeatureNotSupported {
            get {
                return ResourceManager.GetString("FeatureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter test cases.
        /// </summary>
        internal static string FilterTestCases {
            get {
                return ResourceManager.GetString("FilterTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next &gt;.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test case selected..
        /// </summary>
        internal static string NoTestCaseSelected {
            get {
                return ResourceManager.GetString("NoTestCaseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} test cases in the play list are not found..
        /// </summary>
        internal static string NotFoundCaseMessage {
            get {
                return ResourceManager.GetString("NotFoundCaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play List (*.playlist)|*.playlist.
        /// </summary>
        internal static string PlaylistFilter {
            get {
                return ResourceManager.GetString("PlaylistFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running test cases....
        /// </summary>
        internal static string RunningTestCases {
            get {
                return ResourceManager.GetString("RunningTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run selected test cases.
        /// </summary>
        internal static string RunSelectedTestCases {
            get {
                return ResourceManager.GetString("RunSelectedTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this test suite using the settings of last run..
        /// </summary>
        internal static string RunToolTip {
            get {
                return ResourceManager.GetString("RunToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a test suite to launch.
        /// </summary>
        internal static string SelectTestSuite {
            get {
                return ResourceManager.GetString("SelectTestSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string StopDetectButton {
            get {
                return ResourceManager.GetString("StopDetectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} test cases are selected.
        ///{1} ptfconfig items are changed..
        /// </summary>
        internal static string SummaryFormat {
            get {
                return ResourceManager.GetString("SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished running test cases..
        /// </summary>
        internal static string TestCasesFinished {
            get {
                return ResourceManager.GetString("TestCasesFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test profile (*.ptm)|*.ptm.
        /// </summary>
        internal static string TestProfileFilter {
            get {
                return ResourceManager.GetString("TestProfileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string TestProfileFolder {
            get {
                return ResourceManager.GetString("TestProfileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTM Test Result (*.result)|*.result.
        /// </summary>
        internal static string TestResultsFilter {
            get {
                return ResourceManager.GetString("TestResultsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string TestResultsFolder {
            get {
                return ResourceManager.GetString("TestResultsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test suite introduction.
        /// </summary>
        internal static string TestSuiteIntroduction {
            get {
                return ResourceManager.GetString("TestSuiteIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (*.txt)|*.txt.
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Test Manager - {0} {1}.
        /// </summary>
        internal static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devenv.exe.
        /// </summary>
        internal static string VSFileName {
            get {
                return ResourceManager.GetString("VSFileName", resourceCulture);
            }
        }
    }
}
