trigger: none

variables:
  - group: External Repo Variables

resources:
  repositories:
    - repository: template
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: AzurePipelines-main

jobs:
- job:
  displayName: Verify Pull Requests
  pool:
    vmImage: windows-2022
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
  - template: pipelines/build/PullRequestBuild-steps.yml@template
    parameters:
      extRepoUrl: $(extRepo.url)
