trigger: none
variables:
- group: Build Variables
resources:
  repositories:
  - repository: template
    type: git
    name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
    ref: AzurePipelines-main
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      networkIsolationPolicy: Permissive,CFSClean  
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: ''
        displayName: DotNetCore Build
        workspace:
          clean: false
        timeoutInMinutes: 0
        steps:
        - task: UseDotNet@2
          displayName: 'Install .NET 8 SDK'
          inputs:
            version: '8.0.x'
            installationPath: $(Agent.ToolsDirectory)/dotnet
            performMultiLevelLookup: false
        - task: NuGetAuthenticate@1
        - template: pipelines/build/1es/DotNetCore-MSBuild-Build-steps.yml@template