name: $(date:yyyyMMdd)$(rev:.r)
variables:
  - name: system.debug
    value: false
  - group: Access Tokens
  - group: Azure Account V2
resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: mainPipelines
      type: git
      name: WindowsProtocolTestSuites/WindowsProtocolTestSuites
      ref: AzurePipelines-main
trigger:
  branches:
    include:
      - refs/heads/main
  batch: true
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: windows
      image: windows-2019
      name: Azure-Pipelines-1ESPT-ExDShared
    customBuildTags:
      - MigrationTooling-microsoft-WindowsProtocolTestSuites-53149-Tool
    stages:
      - stage: Stage
        jobs:
          - job: SyncToGithub
            displayName: Sync to Github
            steps:
            - template: pipelines/build/1es/TestSuiteMainSyncToGitHub-steps.yml@mainPipelines
