//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Protocols.TestManager.Kernel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Protocols.TestManager.Kernel.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;Common&quot;&gt;
        ///      &lt;!-- START - OVERALL ENVIRONMENT CONFIG --&gt;
        ///      &lt;Property name=&quot;AllowBreakEnvironment&quot; value=&quot;false&quot;&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AD_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("AD_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property name=&quot;TestName&quot; value=&quot;AD_Family_Test_Suite&quot; /&gt;
        ///    &lt;Property name=&quot;FeatureName&quot; value=&quot;AD_Family&quot; /&gt;
        ///    &lt;Property name=&quot;Version&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AD_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("AD_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to append test category..
        /// </summary>
        internal static string AppendCategoryError {
            get {
                return ResourceManager.GetString("AppendCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;Auth&quot;&gt;
        ///      &lt;Group  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Auth_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("Auth_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties/&gt;
        ///&lt;/TestSite&gt;
        ///.
        /// </summary>
        internal static string Auth_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("Auth_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Properties&gt;
        ///
        ///    &lt;!--
        ///        Please edit the following settings according to your test environment
        ///    --&gt;
        ///
        ///    &lt;!--
        ///        SU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BranchCache_TestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("BranchCache_TestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; 
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  
        ///  &lt;Properties&gt;
        ///    &lt;Property name=&quot;TestName&quot; value=&quot;BranchCache Test&quot; /&gt;
        ///    &lt;Property name=&quot;FeatureName&quot; value=&quot;BranchCache&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BranchCache_TestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("BranchCache_TestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///
        ///    &lt;!--
        ///        Tag named Choice is used for the ComboBox in UI design
        ///        Tag named Description is used for the com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("CommonTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Properties&gt;
        ///
        ///    &lt;Group name=&quot;Common&quot;&gt;
        ///      &lt;Property name=&quot;TestName&quot; value=&quot;FileServer Family Test&quot; /&gt;
        ///      &lt;Property name=&quot;Feat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("CommonTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.xml.
        /// </summary>
        internal static string ConfigFilename {
            get {
                return ResourceManager.GetString("ConfigFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configFileNames must not be null..
        /// </summary>
        internal static string ConfigFileNameNotSpecified {
            get {
                return ResourceManager.GetString("ConfigFileNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the test suite:
        ///{0}.
        /// </summary>
        internal static string ConfigLoadError {
            get {
                return ResourceManager.GetString("ConfigLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0} test suite..
        /// </summary>
        internal static string DefaultDescription {
            get {
                return ResourceManager.GetString("DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Group.
        /// </summary>
        internal static string DefaultGroupName {
            get {
                return ResourceManager.GetString("DefaultGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.
        /// </summary>
        internal static string DefaultNamespace {
            get {
                return ResourceManager.GetString("DefaultNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} is not found..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated node with type = &quot;{0}&quot;, name = &quot;{1}&quot; found..
        /// </summary>
        internal static string DuplicatePTFConfigNode {
            get {
                return ResourceManager.GetString("DuplicatePTFConfigNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Server)|(Client).
        /// </summary>
        internal static string EndpointRegex {
            get {
                return ResourceManager.GetString("EndpointRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TestFailed].
        /// </summary>
        internal static string FailedTag {
            get {
                return ResourceManager.GetString("FailedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common7\IDE\Extensions\TestPlatform\Extensions\Microsoft.Protocols.TestTools.Html.TestLogger.dll.
        /// </summary>
        internal static string HtmlTestLoggerLocation {
            get {
                return ResourceManager.GetString("HtmlTestLoggerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find html test logger, try to reinstall Protocol Test Framework..
        /// </summary>
        internal static string HtmlTestLoggerNotInstalled {
            get {
                return ResourceManager.GetString("HtmlTestLoggerNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TestInconclusive].
        /// </summary>
        internal static string InconclusiveTag {
            get {
                return ResourceManager.GetString("InconclusiveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TestInProgress].
        /// </summary>
        internal static string InprogressTag {
            get {
                return ResourceManager.GetString("InprogressTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not a valid PTM test profile..
        /// </summary>
        internal static string InvalidProfile {
            get {
                return ResourceManager.GetString("InvalidProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;!--Common properties--&gt;
        ///    &lt;Property name=&quot;TransportType&quot; value=&quot;tcp&quot;&gt;
        ///      &lt;Description&gt;
        ///        The default transport type
        ///      &lt;/Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kerberos_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("Kerberos_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property name=&quot;ConsoleBufferHeight&quot; value=&quot;600&quot;/&gt;
        ///    &lt;!--The directory of the keytab files. Leave empty to make keys  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kerberos_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("Kerberos_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load adapters from the test suite assembly:
        ///{0}.
        /// </summary>
        internal static string LoadAdapterError {
            get {
                return ResourceManager.GetString("LoadAdapterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the test suite assembly:
        ///{0}.
        /// </summary>
        internal static string LoadAssemblyError {
            get {
                return ResourceManager.GetString("LoadAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the feature mapping from the config.xml:
        ///{0}.
        /// </summary>
        internal static string LoadFeatureMappingError {
            get {
                return ResourceManager.GetString("LoadFeatureMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the filter definitions from the config.xml:
        ///{0}.
        /// </summary>
        internal static string LoadFilterError {
            get {
                return ResourceManager.GetString("LoadFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading auto-detector assembly failed..
        /// </summary>
        internal static string LoadingAutoDetectorFailed {
            get {
                return ResourceManager.GetString("LoadingAutoDetectorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in loading profile: {0}.
        /// </summary>
        internal static string LoadProfileError {
            get {
                return ResourceManager.GetString("LoadProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the PTFConfig files:
        ///{0}.
        /// </summary>
        internal static string LoadPtfconfigError {
            get {
                return ResourceManager.GetString("LoadPtfconfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Properties&gt;    
        ///    &lt;Group name=&quot;Domain&quot;&gt;
        ///      &lt;Property name=&quot;DomainName&quot;        value=&quot;contoso.com&quot;/&gt;
        ///      &lt;Property name=&quot;Usern [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_ADFSPIP_ClientTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_ADFSPIP_ClientTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;!-- Test suite properties which value not changed when running in different test environments --&gt;
        ///    &lt;!--&lt;Property na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_ADFSPIP_ClientTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_ADFSPIP_ClientTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;!--Basic Configuration.--&gt;
        ///
        ///    &lt;!--Category: Domain Information.--&gt;
        ///    &lt;!--Scope: All scope (Windows, NonWindows).- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_ADOD_ODTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_ADOD_ODTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; 
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  
        ///  &lt;Properties&gt;
        ///    &lt;Property name=&quot;TestName&quot; value=&quot;MS-ADOD Test&quot; /&gt;
        ///    &lt;Property name=&quot;ExpectedExecutionTime&quot; value=&quot;1200&quot; /&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_ADOD_ODTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_ADOD_ODTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;!-- Windows configuration --&gt;
        ///      &lt;!--Basic configuration--&gt;       
        ///        &lt;!--Scope: KDC domain--&gt;
        ///        &lt;!- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_AZOD_ODTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_AZOD_ODTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; 
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  
        ///  &lt;Properties&gt;
        ///    &lt;Property name=&quot;TestName&quot; value=&quot;MS-AZOD Test&quot; /&gt;
        ///  &lt;/Properties&gt;
        ///
        ///  &lt;Adapters&gt;
        ///    &lt;!--&lt;Adapter xsi:type=&quot;int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_AZOD_ODTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_AZOD_ODTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;DFSC&quot;&gt;
        ///      &lt;!--T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_DFSC_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_DFSC_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties/&gt;
        ///&lt;/TestSite&gt;
        ///.
        /// </summary>
        internal static string MS_DFSC_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_DFSC_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;FSA&quot;&gt;
        ///      &lt;Proper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_FSA_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_FSA_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; 
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties /&gt;
        ///  
        ///  &lt;Adapters&gt;
        ///    &lt;Adapter xsi:type=&quot;man [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_FSA_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_FSA_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///  &lt;Properties&gt;
        ///    &lt;!--
        ///        Please edit the follow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_FSRVP_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_FSRVP_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties/&gt;
        ///&lt;/TestSite&gt;
        ///.
        /// </summary>
        internal static string MS_FSRVP_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_FSRVP_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;RSVD&quot;&gt;
        ///      &lt;Prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_RSVD_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_RSVD_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties/&gt;
        ///&lt;/TestSite&gt;
        ///.
        /// </summary>
        internal static string MS_RSVD_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_RSVD_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;SMB2&quot;&gt;
        ///      &lt;!--Tag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_SMB2_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SMB2_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties/&gt;
        ///&lt;/TestSite&gt;
        ///.
        /// </summary>
        internal static string MS_SMB2_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SMB2_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;SMB2&quot;&gt;
        ///      &lt;!--Tag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_SMB2Model_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SMB2Model_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties/&gt;
        ///  
        ///  &lt;Adapters&gt;
        ///    &lt;Adapter xsi:type=&quot;managed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_SMB2Model_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SMB2Model_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot; 
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;!--Computer name of system under test (SUT)--&gt;
        ///    &lt;Property name=&quot;SutComputerName&quot; value=&quot;SMBD-SUT01&quot; /&gt;
        ///    &lt;!--I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_SMBD_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SMBD_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property name=&quot;TestName&quot; value=&quot;SMBD&quot; /&gt;
        ///    &lt;Property name=&quot;FeatureName&quot; value=&quot;MS-SMBD&quot; /&gt;
        ///
        ///    &lt;!--Security packag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_SMBD_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SMBD_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;SQOS&quot;&gt;
        ///      &lt;Prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MS_SQOS_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SQOS_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties/&gt;
        ///&lt;/TestSite&gt;
        ///.
        /// </summary>
        internal static string MS_SQOS_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("MS_SQOS_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TestPassed].
        /// </summary>
        internal static string PassedTag {
            get {
                return ResourceManager.GetString("PassedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTFToolPipe.
        /// </summary>
        internal static string PipeName {
            get {
                return ResourceManager.GetString("PipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile version is newer than test suite..
        /// </summary>
        internal static string ProfileNewerError {
            get {
                return ResourceManager.GetString("ProfileNewerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile does not match the installed test suite.
        ///The profile is for {0} {1}.
        ///The test suite is {2} {3}..
        /// </summary>
        internal static string ProfileNotMatchError {
            get {
                return ResourceManager.GetString("ProfileNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of Protocol Test Manager ({0}) is lesser than version of the test suite ({1}).
        ///Please upgrade Protocol Test Manager to the same version with the test suite..
        /// </summary>
        internal static string PTMNeedUpgrade {
            get {
                return ResourceManager.GetString("PTMNeedUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Properties&gt;
        ///
        ///    &lt;!--Block Begin: Properties that required to be set ***--&gt;
        ///    &lt;!--The RDP listening port number.--&gt;
        ///    &lt;Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RDP_ClientTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("RDP_ClientTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;!-- Test suite properties which value not changed when running in different test environments --&gt;
        ///    &lt;!--&lt;Property na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RDP_ClientTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("RDP_ClientTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Properties&gt;
        ///
        ///    &lt;!--Block Begin: Properties that required to be set ***--&gt;
        ///    &lt;!--Whether a negotiation protocol is used.--&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RDP_ServerTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("RDP_ServerTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Properties&gt;
        ///    &lt;!-- Test suite properties which value not changed when running in different test environments --&gt;
        ///    &lt;!--&lt;Property na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RDP_ServerTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("RDP_ServerTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultRegistryPath is not specified..
        /// </summary>
        internal static string RegistryPathNotSpecified {
            get {
                return ResourceManager.GetString("RegistryPathNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.deployment.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///
        ///    &lt;Group name=&quot;Cluster&quot;&gt;
        ///      &lt;! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServerFailoverTestSuite_deployment_ptfconfig {
            get {
                return ResourceManager.GetString("ServerFailoverTestSuite_deployment_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TestSite xmlns=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig http://schemas.microsoft.com/windows/ProtocolsTest/2007/07/TestConfig.xsd&quot;&gt;
        ///
        ///  &lt;Include&gt;
        ///    &lt;File name=&quot;CommonTestSuite.ptfconfig&quot;/&gt;
        ///  &lt;/Include&gt;
        ///
        ///  &lt;Properties&gt;
        ///    &lt;Group name=&quot;Cluster&quot;&gt;
        ///      &lt;Property nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServerFailoverTestSuite_ptfconfig {
            get {
                return ResourceManager.GetString("ServerFailoverTestSuite_ptfconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\MicrosoftProtocolTests\{0}\{1}-Endpoint\{2}.
        /// </summary>
        internal static string TestSuiteFolder {
            get {
                return ResourceManager.GetString("TestSuiteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of Protocol Test Manager ({0}) is greater than version of the test suite ({1}).
        ///Please upgrade the test suite to the same version of Protocol Test Manager..
        /// </summary>
        internal static string TestSuiteNeedUpgrade {
            get {
                return ResourceManager.GetString("TestSuiteNeedUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d+\.\d+\.\d+\.\d+.
        /// </summary>
        internal static string VersionRegex {
            get {
                return ResourceManager.GetString("VersionRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe.
        /// </summary>
        internal static string VSTestLocation {
            get {
                return ResourceManager.GetString("VSTestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the test engine vstest.console.exe..
        /// </summary>
        internal static string VSTestNotInstalled {
            get {
                return ResourceManager.GetString("VSTestNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema-instance.
        /// </summary>
        internal static string XsiNamespace {
            get {
                return ResourceManager.GetString("XsiNamespace", resourceCulture);
            }
        }
    }
}
